### ISSUE TITLE
Code Review

### ISSUE THREAD

**Issue by ReubenBond** [creyke/Orleans.Sagas#2]
You asked for some review on Twitter. LGTM with some minor comments 

https://github.com/creyke/Orleans.Sagas/blob/a7abcca035d655da81a2cb975dc7caef68ad1cdc/Orleans.Sagas/SagaBuilder.cs#L50

^ Should this check `IsAssignableFrom` instead of type equality? If I have an activity of type `MyActivity<IMyConfig>` then this would break, since the runtime type will never be equal to `IMyConfig` (it could only be some concrete type). Similarly when inheritance is involved.

https://github.com/creyke/Orleans.Sagas/blob/master/Orleans.Sagas/SagaGrain.cs#L67

^ Use the `.Ignore()` extension here and remove the warning.

https://github.com/creyke/Orleans.Sagas/blob/master/Orleans.Sagas/SagaGrain.cs#L56

^ The lock is unnecessary unless there's somewhere where the activation's threading is being violated (eg via `Task.Run` or `new Thread(..)`).

https://github.com/creyke/Orleans.Sagas/blob/a7abcca035d655da81a2cb975dc7caef68ad1cdc/Orleans.Sagas/SagaGrain.cs#L27

^ Do we need to also start compensation here? Should this fail if the saga has already completed?

https://github.com/creyke/Orleans.Sagas/blob/a7abcca035d655da81a2cb975dc7caef68ad1cdc/Orleans.Sagas/ISagaBuilder.cs#L24

^ This could be more strongly typed, but maybe it's not desirable since you'd need to explicitly provide two generic parameters:
```C#
void AddActivity<TActivity, TConfig>(TConfig config) where TActivity : IActivity<TConfig>;

// Usage:
builder.AddActivity<MyActivity, MyConfig)(myConfig);
```

We could expand the API to allow DAGs of activities instead of only a linear set. Maybe that could be achieved by using an `Activity` which can itself contain a sub-saga. In that implementation it might be better to pass fully constructed `IActivity` objects to the saga so that the deserialization can handle correctly configuring the grain references to the sub sagas. That would also remove the need for `Activator.CreateInstance` and the generic `IActivity<TConfig>` variant of the interface.

**Comment by creyke** [comment]
Taken on board and added or raised as issues. Appreciated!
